---
language: node_js
node_js:
  - "4"

env:
  - TESTING=testing-travis  

sudo: false

cache:
  directories:
    - node_modules

before_install:
  - npm config set spin false
  - npm install -g bower
  - npm install phantomjs-prebuilt

install:
  - npm install
  - bower install

script:
  - npm test
